[project]
name = "gping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.0",
    "pillow>=10.0.0",
    "pyinstaller>=6.11.0",
    "pystray>=0.19.5",
]
